[features]
seeds = false
skip-lint = false
[programs.localnet]
sf = "FCLsYGgoyrfT6MjftqVTFs3kCwc9HC8hRfYyYGPi85QE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/eren/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
